### ISSUE TITLE
Add ipfsspec to install requirements

### ISSUE THREAD

**Issue by Geet-George** [eurec4a/pyeurec4a#2]
My conda environment did not have [ipfsspec](https://pypi.org/project/ipfsspec/) originally. While using the `use_ipfs` option with a CID in the `get_intake_catalog` function, it showed me the following error:

`ValueError: Protocol not known: ipfs`

This was fixed after I installed `ipfsspec` in the environment. 

Should this package then be included in the `install_requires` list in setup.py, which currently looks like 👇 ?

```
install_requires=[
        "requests",
        "pyyaml",
        "intake!=0.6.1",  # due to lacking jinja2 dependency
        "aiohttp",  # required by intake to access catalogs via http
    ]
```

P.S. This is only needed if the CID is provided, but considering that `ipfs` is a strong point of the function, it would be a nice addition to the requirements.

**Comment by d70-t** [comment]
Thanks for reporting this 👍
When touching that list the last time, IPFS was not yet used so commonly, that's why it has been optional. But I guess this has changed now.
